# alternatively, `export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-server-runner`

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"


# fix spurious network error on windows
# [source.crates-io]
# registry = "https://github.com/rust-lang/crates.io-index"

[http]
proxy = ""
